import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { QueryProvider } from "@/query/QueryProvider";
import { ToastContainer } from "react-toastify";
import { GlobalContext } from "@/context/Context";
import Header from "@/module/Header/Header";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ashyo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalContext>
          <QueryProvider>
            <Header />
            <ToastContainer
              position="bottom-right"
              autoClose={2000}
            />
            {children}
          </QueryProvider>
        </GlobalContext>
      </body>
    </html>
  );
}
